# Generated by Django 4.2.30 on 2026-06-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_entries_per_day', models.IntegerField(default=1, help_text='0 = unlimited')),
                ('priority_level', models.IntegerField(default=0, help_text='Higher = more priority')),
                ('has_unlimited_access', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority_level'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='e.g., 16TAC123', max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('van', 'Van')], default='car', max_length=20)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('is_registered', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.subscriptionplan')),
            ],
            options={
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['plate_number'], name='vehicles_ve_plate_n_a3accc_idx'), models.Index(fields=['is_banned'], name='vehicles_ve_is_bann_ea2df1_idx')],
            },
        ),
    ]
