# Generated by Django 6.0.5 on 2026-05-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='e.g., 16TAC123', max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('van', 'Van')], default='car', max_length=20)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('is_registered', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['plate_number'], name='vehicles_ve_plate_n_a3accc_idx'), models.Index(fields=['is_banned'], name='vehicles_ve_is_bann_ea2df1_idx')],
            },
        ),
    ]
