# Generated by Django 6.0.5 on 2026-05-13 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(default='07:00')),
                ('close_time', models.TimeField(default='22:00')),
                ('max_capacity', models.IntegerField(default=50)),
                ('current_count', models.IntegerField(default=0)),
                ('is_manual_open', models.BooleanField(default=False)),
                ('is_manual_closed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parking Configuration',
                'verbose_name_plural': 'Parking Configuration',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_detected', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('DENIED', 'Denied')], max_length=10)),
                ('denial_reason', models.CharField(blank=True, choices=[('NOT_REGISTERED', 'Not registered'), ('BANNED', 'Vehicle banned'), ('OUTSIDE_HOURS', 'Outside operating hours'), ('PARKING_FULL', 'Parking full'), ('LOW_CONFIDENCE', 'Low OCR confidence'), ('MANUAL_CLOSED', 'Manually closed'), ('UNKNOWN', 'Unknown')], max_length=30)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gate', models.CharField(default='MAIN', max_length=20)),
                ('processed_by', models.CharField(default='AUTO', max_length=20)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='access_acce_timesta_0603e5_idx'), models.Index(fields=['plate_detected'], name='access_acce_plate_d_b3eac4_idx')],
            },
        ),
    ]
