# Generated by Django 4.2.30 on 2026-06-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('max_capacity', models.IntegerField(default=50)),
                ('current_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(default='07:00')),
                ('close_time', models.TimeField(default='22:00')),
                ('max_capacity', models.IntegerField(default=50)),
                ('current_count', models.IntegerField(default=0)),
                ('is_manual_open', models.BooleanField(default=False)),
                ('is_manual_closed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parking Configuration',
                'verbose_name_plural': 'Parking Configuration',
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('ENTRANCE', 'Entrance'), ('EXIT', 'Exit')], default='ENTRANCE', max_length=10)),
                ('camera_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the camera (e.g., 192.168.1.100)', null=True)),
                ('camera_port', models.IntegerField(default=554)),
                ('camera_username', models.CharField(blank=True, max_length=100)),
                ('camera_password', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('open_time', models.TimeField(default='07:00')),
                ('close_time', models.TimeField(default='22:00')),
                ('allowed_vehicle_types', models.CharField(blank=True, help_text='Comma-separated vehicle types allowed (leave blank for all)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='access.zone')),
            ],
            options={
                'ordering': ['zone__name', 'name'],
                'unique_together': {('zone', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_detected', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('DENIED', 'Denied')], max_length=10)),
                ('denial_reason', models.CharField(blank=True, choices=[('NOT_REGISTERED', 'Not registered'), ('BANNED', 'Vehicle banned'), ('OUTSIDE_HOURS', 'Outside operating hours'), ('PARKING_FULL', 'Parking full'), ('LOW_CONFIDENCE', 'Low OCR confidence'), ('MANUAL_CLOSED', 'Manually closed'), ('SUBSCRIPTION_EXPIRED', 'Subscription expired'), ('DAILY_LIMIT_REACHED', 'Daily entry limit reached'), ('VEHICLE_TYPE_NOT_ALLOWED', 'Vehicle type not allowed at this gate'), ('UNKNOWN', 'Unknown')], max_length=30)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gate', models.CharField(default='MAIN', max_length=20)),
                ('processed_by', models.CharField(default='AUTO', max_length=20)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='access.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='access_acce_timesta_0603e5_idx'), models.Index(fields=['plate_detected'], name='access_acce_plate_d_b3eac4_idx')],
            },
        ),
    ]
